# Generated by Django 4.0.6 on 2022-07-31 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_remove_cart_items_cart_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catergory',
            old_name='kategory',
            new_name='category',
        ),
    ]
