# Generated by Django 4.0.1 on 2022-02-09 03:38

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_register_user_delete_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=100, verbose_name=blogs.models.Blog),
        ),
    ]
