# Generated by Django 4.0.1 on 2022-01-15 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprasial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('employee_imaage', models.ImageField(blank=True, upload_to='images/employees')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_from', models.CharField(max_length=150)),
                ('transport_to', models.CharField(max_length=150)),
                ('vehicle', models.CharField(choices=[('B', 'Bus'), ('C', 'Cab')], max_length=1)),
                ('cost_of_transport', models.DecimalField(decimal_places=1, max_digits=150)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OverTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timefrom', models.TimeField()),
                ('timeto', models.TimeField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askedfor', to='employee.availablematerial')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askedby', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavedate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('leavetype', models.CharField(choices=[('S', 'Sick'), ('C', 'Casual'), ('E', 'Emergency'), ('M', 'Maternity')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='pending', max_length=1)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='employee.employee')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('attendance_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ApprasialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1023)),
                ('answer', models.CharField(blank=True, max_length=1023)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='employee.apprasial')),
            ],
        ),
        migrations.CreateModel(
            name='ApprasialResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('P', 'Promoted'), ('S', 'Salary Hike'), ('N', 'No Hike')], max_length=1)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.apprasial')),
            ],
        ),
        migrations.AddField(
            model_name='apprasial',
            name='appraisee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='apprasial',
            name='appraiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals_taken', to='employee.employee'),
        ),
    ]
