# Generated by Django 4.0.1 on 2022-01-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_overtime_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
